// Code generated by internal/cenum2go/main.go DO NOT EDIT.
package zstd

type ZSTD_ErrorCode int

const (
	ZSTD_ErrorCode_no_error                        ZSTD_ErrorCode = 0
	ZSTD_ErrorCode_error_GENERIC                   ZSTD_ErrorCode = 1
	ZSTD_ErrorCode_prefix_unknown                  ZSTD_ErrorCode = 10
	ZSTD_ErrorCode_version_unsupported             ZSTD_ErrorCode = 12
	ZSTD_ErrorCode_frameParameter_unsupported      ZSTD_ErrorCode = 14
	ZSTD_ErrorCode_frameParameter_windowTooLarge   ZSTD_ErrorCode = 16
	ZSTD_ErrorCode_corruption_detected             ZSTD_ErrorCode = 20
	ZSTD_ErrorCode_checksum_wrong                  ZSTD_ErrorCode = 22
	ZSTD_ErrorCode_literals_headerWrong            ZSTD_ErrorCode = 24
	ZSTD_ErrorCode_dictionary_corrupted            ZSTD_ErrorCode = 30
	ZSTD_ErrorCode_dictionary_wrong                ZSTD_ErrorCode = 32
	ZSTD_ErrorCode_dictionaryCreation_failed       ZSTD_ErrorCode = 34
	ZSTD_ErrorCode_parameter_unsupported           ZSTD_ErrorCode = 40
	ZSTD_ErrorCode_combination_unsupported         ZSTD_ErrorCode = 41
	ZSTD_ErrorCode_parameter_outOfBound            ZSTD_ErrorCode = 42
	ZSTD_ErrorCode_tableLog_tooLarge               ZSTD_ErrorCode = 44
	ZSTD_ErrorCode_maxSymbolValue_tooLarge         ZSTD_ErrorCode = 46
	ZSTD_ErrorCode_maxSymbolValue_tooSmall         ZSTD_ErrorCode = 48
	ZSTD_ErrorCode_stabilityCondition_notRespected ZSTD_ErrorCode = 50
	ZSTD_ErrorCode_stage_wrong                     ZSTD_ErrorCode = 60
	ZSTD_ErrorCode_init_missing                    ZSTD_ErrorCode = 62
	ZSTD_ErrorCode_memory_allocation               ZSTD_ErrorCode = 64
	ZSTD_ErrorCode_workSpace_tooSmall              ZSTD_ErrorCode = 66
	ZSTD_ErrorCode_dstSize_tooSmall                ZSTD_ErrorCode = 70
	ZSTD_ErrorCode_srcSize_wrong                   ZSTD_ErrorCode = 72
	ZSTD_ErrorCode_dstBuffer_null                  ZSTD_ErrorCode = 74
	ZSTD_ErrorCode_noForwardProgress_destFull      ZSTD_ErrorCode = 80
	ZSTD_ErrorCode_noForwardProgress_inputEmpty    ZSTD_ErrorCode = 82
	ZSTD_ErrorCode_frameIndex_tooLarge             ZSTD_ErrorCode = 100
	ZSTD_ErrorCode_error_seekableIO                ZSTD_ErrorCode = 102
	ZSTD_ErrorCode_dstBuffer_wrong                 ZSTD_ErrorCode = 104
	ZSTD_ErrorCode_srcBuffer_wrong                 ZSTD_ErrorCode = 105
	ZSTD_ErrorCode_sequenceProducer_failed         ZSTD_ErrorCode = 106
	ZSTD_ErrorCode_externalSequences_invalid       ZSTD_ErrorCode = 107
	ZSTD_ErrorCode_error_maxCode                   ZSTD_ErrorCode = 120
)
