// Code generated by internal/cenum2go/main.go DO NOT EDIT.
package zstd

type ZSTD_strategy int

const (
	ZSTD_strategy_fast     ZSTD_strategy = 1
	ZSTD_strategy_dfast    ZSTD_strategy = 2
	ZSTD_strategy_greedy   ZSTD_strategy = 3
	ZSTD_strategy_lazy     ZSTD_strategy = 4
	ZSTD_strategy_lazy2    ZSTD_strategy = 5
	ZSTD_strategy_btlazy2  ZSTD_strategy = 6
	ZSTD_strategy_btopt    ZSTD_strategy = 7
	ZSTD_strategy_btultra  ZSTD_strategy = 8
	ZSTD_strategy_btultra2 ZSTD_strategy = 9
)
